# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docs CI
on:
  workflow_call: {}
  workflow_dispatch:

permissions: {}

concurrency:
  group: docs-ci-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  dprint:
    name: dprint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read # Required to checkout the repository
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
        with:
          install_args: dprint
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check formatting
        run: dprint check
