# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Pull Request Labeler"
on:
  - pull_request

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  labeler:
    name: labeler
    permissions:
      contents: read # Required to read repository contents and configuration
      pull-requests: write # Required to apply labels to pull requests
      issues: write # Required to apply labels to issues
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
