# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Prebuild DevContainer
on:
  workflow_call: {}
  workflow_dispatch:
    inputs:
      no_cache:
        description: "Disable cache for container build"
        required: true
        default: false
        type: boolean

permissions:
  contents: read # Required to checkout the repository

concurrency:
  group: prebuild-container-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  prebuild:
    name: prebuild
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read # Required to checkout the repository
      packages: write # Required to push container images to registry

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Convert repository owner/repo to lowercase
        id: repo_name
        run: |
          echo "lowercase=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          imageName: ghcr.io/${{ steps.repo_name.outputs.lowercase }}/devcontainer
          cacheFrom: ghcr.io/${{ steps.repo_name.outputs.lowercase }}/devcontainer
          refFilterForPush: refs/heads/main
          noCache: ${{ github.event.inputs.no_cache == 'true' }}
